export const GITHUB_PROFILE_URL = 'https://github.com/Iv44n'
export const INSTAGRAM_URL = 'https://www.instagram.com/iv4n.dev'
export const LINKEDIN_URL = 'https://www.linkedin.com/in/iv4n-dev'
export const EMAIL_URL = 'mailto:ivandev2oo6@gmail.com'
export const PHONE_URL = 'tel:+51927416434'
export const WHATSAPP_URL = 'https://wa.me/51927416434'
export const WEBSITE_URL = 'https://iv4n.dev'
export const CV_URL = '/cv.pdf'
