import type { JSX } from 'react'
import { FaJava } from 'react-icons/fa'
import { GiWatermelon } from 'react-icons/gi'
import {
  SiAstro,
  SiAxios,
  SiBun,
  SiDocker,
  SiExpo,
  SiExpress,
  SiGit,
  SiGithub,
  SiGo,
  SiHono,
  SiJavascript,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiNotion,
  SiPostgresql,
  SiReact,
  SiReactquery,
  SiRedis,
  SiRender,
  SiSpringboot,
  SiSpringsecurity,
  SiSqlite,
  SiTailwindcss,
  SiTypescript,
  SiVercel
} from 'react-icons/si'
import { TbApi, TbBrandReactNative } from 'react-icons/tb'
import { VscJson } from 'react-icons/vsc'

export const SKILL_ICON_MAP: Record<string, JSX.Element> = {
  JavaScript: <SiJavascript />,
  TypeScript: <SiTypescript />,
  React: <SiReact />,
  'Next.js': <SiNextdotjs />,
  Astro: <SiAstro />,
  'Tailwind CSS': <SiTailwindcss />,
  'Node.js': <SiNodedotjs />,
  Bun: <SiBun />,
  Express: <SiExpress />,
  'Spring Boot': <SiSpringboot />,
  'Spring Security': <SiSpringsecurity />,
  JWT: <VscJson />,
  'REST APIs': <TbApi />,
  MongoDB: <SiMongodb />,
  PostgreSQL: <SiPostgresql />,
  SQLite: <SiSqlite />,
  WatermelonDB: <GiWatermelon />,
  Git: <SiGit />,
  GitHub: <SiGithub />,
  Vercel: <SiVercel />,
  Docker: <SiDocker />,
  Java: <FaJava />,
  'React Native': <TbBrandReactNative />,
  Expo: <SiExpo />,
  Axios: <SiAxios />,
  'TanStack Query': <SiReactquery />,
  Hono: <SiHono />,
  Render: <SiRender />,
  MySQL: <SiMysql />,
  Redis: <SiRedis />,
  'Go (Básico)': <SiGo />,
  Notion: <SiNotion />,
  NestJS: <SiNestjs />
}
